name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '21'  # Используем Java 21

      - name: Install dependencies
        run: pip install flet==0.8.0

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.6'

      - name: Accept Android SDK Licenses
        run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Install Android SDK components
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2" "ndk;25.1.8937393"

      - name: Install build tools
        run: flutter doctor -v

      - name: Prepare Android Build
        run: |
          # Обновление build.gradle перед сборкой APK
          sed -i '/compileOptions {/a \
              sourceCompatibility JavaVersion.VERSION_21\
              targetCompatibility JavaVersion.VERSION_21\
          ' android/app/build.gradle

          # Игнорирование llvm-strip для libpythonbundle.so
          echo -e "\nandroid {\n    packagingOptions {\n        doNotStrip '**/libpythonbundle.so'\n    }\n}" >> android/app/build.gradle

      - name: Build APK
        env:
          JAVA_HOME: /usr/lib/jvm/temurin-21-jdk  # Указываем путь к Java 21
        run: |
          flutter pub get
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
