name: APK Build

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.11.6
  FLUTTER_VERSION: 3.22.2
  ANDROID_SDK_ROOT: $HOME/Android/sdk
  NDK_VERSION: 25.2.9519653
  SDK_VERSION: android-33

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        architecture: x64

    - name: Setup Java JDK
      uses: actions/setup-java@v4.2.1
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Install Command-Line Tools
      run: |
        mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d $ANDROID_SDK_ROOT/cmdline-tools/
        rm cmdline-tools.zip
        mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools/* $ANDROID_SDK_ROOT/cmdline-tools/
        rmdir $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools

    - name: Verify Command-Line Tools Installation
      run: |
        echo "Listing sdkmanager directory:"
        ls -l $ANDROID_SDK_ROOT/cmdline-tools
        echo "Listing bin directory:"
        ls -l $ANDROID_SDK_ROOT/cmdline-tools/bin
        echo "Checking sdkmanager version:"
        $ANDROID_SDK_ROOT/cmdline-tools/bin/sdkmanager --version || echo "sdkmanager not found or not working"

    - name: Install SDK and NDK Packages
      run: |
        export PATH="$ANDROID_SDK_ROOT/cmdline-tools/bin:$PATH"
        echo "Updated PATH: $PATH"
        sdkmanager --version
        sdkmanager --list
        sdkmanager --update
        sdkmanager --install "ndk;$NDK_VERSION" "platforms;$SDK_VERSION"

    - name: Build APK
      run: |
        flutter config --no-analytics
        flet build apk --verbose

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: apk-build-artifact
        path: build/apk
        if-no-files-found: error
        overwrite: false
